### PR TITLE
Added PhD Student

### PR DESCRIPTION
**Pull request by dobios**
I'm adding two PhD students in Programming languages to the list, me and another woman I collaborate with.

### CODE REVIEW

**Comment by wenkokke** [comment]
Have you checked with Bea?

**Comment by dobios** [comment]
> Have you checked with Bea?

I'll email her to make sure.

**Comment by wenkokke** [comment]
> > Have you checked with Bea?
> 
> I'll email her to make sure.

Any response? If not, you're more then welcome to break this PR up so I can merge you into the list in the meantime.

**Comment by dobios** [comment]
Oh yes sorry, I made her aware of this list, and she will probably add herself once she's less overworked ^^". Thanks for making sure I double checked!!

**Pull request merged**
