### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rxg**
Added Zoe Paraskevopoulou, Princeton

### CODE REVIEW

**Comment by wenkokke** [comment]
Hey @rxg ! Have you checked with Zoe?

**Comment by rxg** [comment]
Will do!

**Comment by rxg** [comment]
Hi Wen,
I've heard back from Zoe and she too would like to be on the list.  Thanks again for all your work on this (and due diligence).

**Comment by wenkokke** [comment]
@rxg Thanks so much for checking in with Zoe and others so quickly, and for your contributions!

**Pull request merged**
